name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az login --service-principal
            az account show
            az az aks get-credentials -n ${{ secrets.AKS_NAME }} -g ${{ secrets.AKS_RG }}
            kubectl apply -f FILEPATH??